[Writable]
LogLevel = 'DEBUG'
[Service]
Host = "10.103.240.124"
Port = 50005
ConnectRetries = 3
Labels = []
OpenMsg = "device simple started"
MaxResultCount = 50000
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "10.103.240.124"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "10.103.240.124"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "10.103.240.124"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "10.103.240.124"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "../../app/device/device-20191104/res"

[Logging]
EnableRemote = false
File = "./device-simple.log"
Level = "DEBUG"

#Pre-define Devices
[[DeviceList]]
  Name = "RandNum-Device01"
  Profile = "RandNum-Device"
  Description = "Random Number Generator Device"
  Labels = [ "random", "test" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.Other]
      Address = "random"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Resource = "Random"
    OnChange = false
    Frequency = "10s"

